apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gecko.fullname" . }}-db-init-data
data:
  # Reads content from the chart filesystem at files/init-data/nav.json
  nav.json: |
{{ .Files.Get "files/init-data/nav.json" | trim | nindent 4 }}

  # Reads content from the chart filesystem at files/init-data/file_summary.json
  file_summary.json: |
{{ .Files.Get "files/init-data/file_summary.json" | trim | nindent 4 }}

  # Reads content from the chart filesystem at files/init-data/apps_page.json
  apps_page.json: |
{{ .Files.Get "files/init-data/apps_page.json" | trim | nindent 4 }}