apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-storage-pv
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: "default"
spec:
  capacity:
    storage: 26Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "qdrant-manual-storage"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/qdrant-local"
