apiVersion: v1
kind: Service
metadata:
  name: workspace-proxy-service
  namespace: {{ .Values.deploymentNamespace }}
  labels:
    app: workspace-proxy
spec:
  type: ClusterIP
  selector:
    app: workspace-proxy
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
