{{- if and .Values.global.externalSecrets .Values.global.externalSecrets.deploy .Values.externalSecrets.fhirCreds }}
apiVersion: {{ include "common.externalSecrets.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: gen3-fhir-proxy
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ include "common.SecretStore" . }}
    kind: SecretStore
  target:
    name: fhir-creds
    creationPolicy: Owner
  data:
    - secretKey: service-account.json
      remoteRef:
        key: {{ .Values.externalSecrets.fhirCreds }}
{{- end }}
