{{- if and (not .Values.global.externalSecrets.deploy) (.Values.global.mapboxToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: mapbox-config
stringData:
  mapbox_token: {{ .Values.global.mapboxToken }}
{{- end }}
