apiVersion: v1
kind: Service
metadata:
  name: fhir-proxy
  labels:
    {{- include "fhir-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "fhir-proxy.selectorLabels" . | nindent 4 }}