apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ohdsi-webapi.fullname" . }}
  labels:
    {{- include "ohdsi-webapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ohdsi-webapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ohdsi-webapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: spring_datasource_ohdsi_driverClassName
              value: "{{ .Values.config.datasource.ohdsi.driverClassName }}"
            - name: spring_datasource_ohdsi_url
              value: "{{ .Values.config.datasource.ohdsi.url }}"
            - name: spring_datasource_ohdsi_username
              value: "{{ .Values.config.datasource.ohdsi.username }}"
            - name: spring_datasource_ohdsi_password
              value: "{{ .Values.config.datasource.ohdsi.password }}"
          # Optional: Add resource limits and probes as needed