{{- if or (not .Values.global.externalSecrets.deploy) (and .Values.global.externalSecrets.deploy .Values.externalSecrets.createOhdsiOidcClientSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: ohdsi-oidc-client
{{- end }}
