apiVersion: v1
kind: Service
metadata:
  name: ohdsi-webapi-service
spec:
  type: NodePort
  selector:
    app: ohdsi-webapi
  ports:
    - port: {{ ternary 443 .Values.service.port (and $nginx.enabled $nginx.tls.enabled) }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
