apiVersion: v1
kind: Service
metadata:
  name: "dicom-server-service"
  labels:
    {{- include "dicom-server.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ ternary 443 .Values.service.port (and $nginx.enabled $nginx.tls.enabled) }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
  selector:
    {{- include "dicom-server.selectorLabels" . | nindent 4 }}
