apiVersion: v2
name: etl
description: A Helm chart for gen3 etl

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
version: 0.1.22
=======
version: 0.1.17
>>>>>>> a6ef146d (Increase SPARK_EXECUTOR_MEMORY and SPARK_DRIVER_MEMORY for ETL (#424))
=======
version: 0.1.18
>>>>>>> 1d9d5b3b (Adding Kubeconform Github Action. (#428))
=======
version: 0.1.19
>>>>>>> a6dcdb6f (update version)
=======
version: 0.1.20
>>>>>>> f0075136 (updating garbage collect RoleBinding to use proper namespace. (#486))
=======
version: 0.1.21
>>>>>>> 7fff5bc5 (Updating ES Garbage Cronjob to Always be Enabled. (#494))
=======
version: 0.1.22
>>>>>>> de72d53d (Refactor FENCE_URL configuration in deployment templates for consistency)

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "master"

dependencies: []
