apiVersion: v1
kind: Service
metadata:
  name: hatchery-service
  labels:
    {{- include "hatchery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
  selector:
    {{- include "hatchery.selectorLabels" . | nindent 4 }}
