apiVersion: v1
kind: PersistentVolume
metadata:
  name: funnel-worker-pv-{{`{{.TaskId}}`}}
  labels:
    app: funnel
    taskId: {{`{{.TaskId}}`}}
    namespace: {{`{{.Namespace}}`}}
spec:
  storageClassName: "" # required for static provisioning
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity: # placeholder only — capacity is effectively elastic
    storage: "10Mi"

  mountOptions:
    {{- if eq .Values.Kubernetes.Storage.type "mountpoint_s3" }}
    - allow-delete
    - allow-overwrite       # allow overwriting existing files
    - incremental-upload    # allow appending to existing files
    - allow-other           # allow non-root users to access the mount
    - region={{`{{.Region}}`}}
    - file-mode=0755
    - prefix=funnel-temp-files/
    {{`{{- if .KmsKeyID}}`}}
    - sse aws:kms
    - sse-kms-key-id={{`{{.KmsKeyID}}`}}
    {{`{{- end}}`}}
    {{- end }}

    {{- if eq .Values.Kubernetes.Storage.type "s3files" }}
    - tls
    - noresvport
    {{- end }}

    {{- if .Values.endpoint_url }}
    - endpoint-url={{ .Values.endpoint_url }}
    - force-path-style # avoids DNS resolution issue, see:
    # https://github.com/awslabs/mountpoint-s3/blob/v1.22.2/doc/TROUBLESHOOTING.md#invalid-hostname-for-dns-resolution
    {{- end }}

  csi:
    {{- if eq .Values.Kubernetes.Storage.type "mountpoint_s3" }}
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-{{`{{.TaskId}}`}}
    volumeAttributes:
      bucketName: {{`{{.Bucket}}`}}
      {{- if .Values.authenticationSource }}
      authenticationSource: {{ .Values.authenticationSource }}
      stsRegion: {{ .Values.stsRegion }}
      {{- end }}
    {{- end }}

    {{- if eq .Values.Kubernetes.Storage.type "s3files" }}
    driver: efs.csi.aws.com
    volumeHandle: s3files:{{`{{.S3FilesystemId}}`}}
    volumeAttributes:
      encryptInTransit: "true"
    {{- end }}

  claimRef:
    namespace: {{`{{.Namespace}}`}}
    name: funnel-worker-pvc-{{`{{.TaskId}}`}}