{{- if or (not .Values.global.externalSecrets.deploy) (and .Values.global.externalSecrets.deploy .Values.externalSecrets.createK8sGen3EmbeddingsSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: gen3embeddings-g3auto
stringData:
  {{- $randomPass := printf "%s%s" "gateway:" (randAlphaNum 32)  }}
  base64Authz.txt: {{  $randomPass | quote | b64enc }}
  gen3-embeddings.env: |
    DEBUG={{ .Values.debug}}
    DB_HOST={{ .Values.postgres.host  }}
    DB_USER={{ .Values.postgres.username }}
    GUNICORN_WORKERS={{ .Values.gunicornWorkers}}
    DB_PASSWORD={{ include "gen3-embeddings.postgres.password" .  }}
    DB_DATABASE={{ .Values.postgres.dbname  }}
    ADMIN_LOGINS={{ $randomPass  }}
{{- end }}