{{- if or (not .Values.global.externalSecrets.deploy) (and .Values.global.externalSecrets.deploy .Values.externalSecrets.createK8sMetadataSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: access-backend-g3auto
stringData:
  {{- $randomPass := printf "%s%s" "gateway:" (randAlphaNum 32)  }}
  base64Authz.txt: {{  $randomPass | quote | b64enc }}
  metadata.env: | 
    DEBUG={{ .Values.debug}}
    SUPER_ADMINS={{ .Values.superAdmins }}
    extra_args={{ .Values.extraArgs }}
    ADMIN_USERS={{ .Values.adminUsers }}
    GH_ORG=uc-cdis
    GH_REPO="datastage-users"
    GH_FILE="users/stageprod/user.yaml"
    GH_KEY=
    JWT_ISSUERS="https://localhost/user"
    REVIEW_REQUESTS_ACCESS=
    JWT_SIGNING_KEYS=
    BASE_USERYAML_PATH=user.yaml
{{- end }}