{{- $deploy := .Values.global.externalSecrets.deploy -}}
{{- $noLocal := not .Values.global.externalSecrets.createLocalK8sSecret -}}
{{- if $deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gen3discoveryai-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ include "common.SecretStore" . }}
    kind: SecretStore
  target:
    name: gen3discoveryai-g3auto
    creationPolicy: Owner
  data:
    - secretKey: base64Authz.txt
      remoteRef:
        key: {{ include "gen3discoveryai-g3auto" . }}
        property: base64Authz.txt
    - secretKey: gen3-discovery-ai.env
      remoteRef:
        key: {{ include "gen3discoveryai-g3auto" . }}
        property: gen3-discovery-ai.env
{{- end }}

{{- if and $deploy $noLocal .Values.llmBackend.google.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gen3discoveryai-google-adc
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ include "common.SecretStore" . }}
    kind: SecretStore
  target:
    name: gen3discoveryai-google-adc
    creationPolicy: Owner
  data:
    - secretKey: gen3discoveryai-google-adc
      remoteRef:
        key: {{ include "gen3discoveryai-g3auto" . }}
        property: application_default_credentials.json
{{- end }}

{{- if and $deploy $noLocal .Values.llmBackend.openai.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gen3discoveryai-openai-key
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ include "common.SecretStore" . }}
    kind: SecretStore
  target:
    name: gen3discoveryai-openai-key
    creationPolicy: Owner
  data:
    - secretKey: gen3discoveryai-openai-key
      remoteRef:
        key: {{ include "gen3discoveryai-g3auto" . }}
        property: OPENAI_API_KEY
{{- end }}

{{- if and $deploy $noLocal }}
---
{{ include "common.externalSecret.db" . }}
{{- end }}