{{- $deploy := .Values.global.externalSecrets.deploy -}}
{{- $createSecret := .Values.externalSecrets.createK8sGen3DiscoveryAiSecret -}}
{{- if or (not $deploy) (and $deploy $createSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: gen3discoveryai-g3auto
stringData:
  {{- $randomPass := printf "%s%s" "gateway:" (randAlphaNum 32)  }}
  base64Authz.txt: {{  $randomPass | quote | b64enc }}
  gen3-discovery-ai.env: |
    DEBUG={{ .Values.debug}}
    GUNICORN_WORKERS={{ .Values.gunicornWorkers}}
{{- end }}
{{- if and (.Values.llmBackend.google.enabled) (or (not $deploy) (and $deploy $createSecret)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gen3discoveryai-google-adc
type: Opaque
stringData:
  application_default_credentials.json: {{ .Values.llmBackend.google.adc | quote }}
{{- end }}

{{- if and .Values.llmBackend.openai.enabled (or (not $deploy) (and $deploy $createSecret)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gen3discoveryai-openai-key
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.llmBackend.openai.apiKey | quote }}
{{- end }}
