apiVersion: v2
name: guppy
description: A Helm chart for gen3 Guppy Service

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
version: 0.1.35
=======
version: 0.1.27
>>>>>>> 5db5f7c4 (Updating HPAs for all of our services. (#414))
=======
version: 0.1.28
>>>>>>> d0be3cc5 (Update versions to meet with Lint changes)
=======
version: 0.1.29
>>>>>>> 14bf12cf ( Setup PushSecret for DB init (#433))
=======
version: 0.1.30
>>>>>>> 54d92d69 (Karpenter Tology Spread  (#460))

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "master"

dependencies:
  - name: common
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    version: 0.1.34
=======
    version: 0.1.24
>>>>>>> 5db5f7c4 (Updating HPAs for all of our services. (#414))
=======
    version: 0.1.25
>>>>>>> 950b51ce (Update version of common and gen3 charts)
=======
    version: 0.1.24
>>>>>>> dabe938c (Revert "Update version of common and gen3 charts")
=======
    version: 0.1.25
>>>>>>> d0be3cc5 (Update versions to meet with Lint changes)
=======
    version: 0.1.26
>>>>>>> 14bf12cf ( Setup PushSecret for DB init (#433))
=======
    version: 0.1.28
>>>>>>> 54d92d69 (Karpenter Tology Spread  (#460))
    repository: file://../common
