apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sigv4-proxy-deployment
  annotations:
  {{- with .Values.podAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "aws-sigv4-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aws-sigv4-proxy.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "aws-sigv4-proxy.selectorLabels" . | nindent 8 }}
        {{- include "common.extraLabels" . | nindent 8 }}
        netvpc: "yes"
      {{- if coalesce .Values.metricsEnabled .Values.global.metricsEnabled true }}
      annotations:
      {{- include "common.grafanaAnnotations" . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.global.topologySpread.enabled }}
      {{- include "common.TopologySpread" . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "aws-sigv4-proxy.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      volumes:
        - name: credentials
          secret:
            secretName: {{.Chart.Name}}-aws-config
            optional: true
      containers:
        - name: "esproxy"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.ports}}
          ports:
            {{- toYaml . | nindent 12}}
          {{- end }}
          env:
            - name: ES_HOST
              value: {{ .Values.esEndpoint }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          command: ["/aws-sigv4-proxy"]
          args:
            - "--verbose"
            - "--log-signing-process"
            - "--log-failed-requests"
            - "--name"
            - "es"
            - "--host"
            - {{ .Values.esEndpoint | quote }}
            - "--sign-host"
            - {{ .Values.esEndpoint | quote }}
            - "--port"
            - {{ printf ":%v" (.Values.service.port | default 9200) | quote }}
            - "--region"
            - {{ .Values.awsRegion | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}