apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    {{- include "aws-sigv4-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (eq (include "common.nginxSidecar.servicePortName" .) "https") }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
  selector:
    {{- include "aws-sigv4-proxy.selectorLabels" . | nindent 4 }}
{{- if not .Values.global.dev }}
---
apiVersion: v1
kind: Service
metadata:
  name: gen3-elasticsearch-master
  labels:
    {{- include "aws-sigv4-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (eq (include "common.nginxSidecar.servicePortName" .) "https") }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
  selector:
    {{- include "aws-sigv4-proxy.selectorLabels" . | nindent 4 }}
{{- end }}