apiVersion: v1
kind: Service
metadata:
  name: "ohif-viewer-service"
  labels:
    {{- include "ohif-viewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (and $nginx.enabled $nginx.tls.enabled) }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
      nodePort: null
  selector:
    {{- include "ohif-viewer.selectorLabels" . | nindent 4 }}
