apiVersion: v1
kind: Service
metadata:
  name: audit-service
  labels:
    {{- include "audit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (and $nginx.enabled $nginx.tls.enabled) }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
  selector:
    {{- include "audit.selectorLabels" . | nindent 4 }}
