apiVersion: v1
kind: Service
metadata:
  name: workspace-token-service
  labels:
    {{- include "wts.labels" . | nindent 4 }}
spec:
  selector:
    app: wts
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (eq (include "common.nginxSidecar.servicePortName" .) "https") }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: http