apiVersion: v1
kind: Service
metadata:
  name: workspace-token-service
  labels:
    {{- include "wts.labels" . | nindent 4 }}
spec:
  selector:
    app: wts
  type: {{ .Values.service.type }}
  ports:
    - port: {{ default 80 .Values.service.port }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}