apiVersion: v1
kind: Service
metadata:
  name: jupyter-enterprise-gateway
  namespace: {{ .Values.workspaceNamespace }}
  labels:
    app: enterprise-gateway
spec:
  type: ClusterIP
  selector:
    app: enterprise-gateway
  ports:
    - name: http
      port: 8888
      targetPort: http
      protocol: TCP
