apiVersion: v1
kind: Service
metadata:
  name: sower-service
  labels:
    {{- include "sower.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
  selector:
    {{- include "sower.selectorLabels" . | nindent 4 }}
    