apiVersion: v1
kind: Service
metadata:
  name: sower-service
  labels:
    {{- include "sower.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (eq (include "common.nginxSidecar.servicePortName" .) "https") }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "sower.selectorLabels" . | nindent 4 }}
    