apiVersion: v1
kind: Service
metadata:
  name: embedding-management-service
  labels:
    {{- include "embedding-management-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}
  selector:
    {{- include "embedding-management-service.selectorLabels" . | nindent 4 }}
