# Dependancy Charts
ambassador:
  enabled: true
  service:
    targetPort: 8080

arborist:
  enabled: true
  service:
    targetPort: 8080

argo-wrapper:
  enabled: false
  service:
    targetPort: 8000

audit:
  enabled: false
  service:
    targetPort: 8000

aws-es-proxy:
  enabled: false
  service:
    targetPort: 8080

fence:
  enabled: true
  service:
    targetPort: 8000

cedar:
  enabled: false
  service:
    targetPort: 8000

cohort-middleware:
  enabled: false
  service:
    targetPort: 8080

gen3-analysis:
  enabled: false
  service:
    targetPort: 8000

gen3-user-data-library:
  enabled: false
  service:
    targetPort: 8000

gen3-workflow:
  enabled: false
  service:
    targetPort: 8080

guppy:
  enabled: false
  service:
    targetPort: 8080

hatchery:
  enabled: true
  service:
    targetPort: 8000

indexd:
  enabled: true
  service:
    targetPort: 8000

manifestservice:
  enabled: false
  service:
    targetPort: 8000

metadata:
  enabled: false
  service:
    targetPort: 8000

ohdsi-atlas:
  enabled: false
  service:
    targetPort: 8080

ohdsi-webapi:
  enabled: false
  service:
    targetPort: 8080

orthanc:
  enabled: false
  service:
    targetPort: 8042

peregrine:
  enabled: true
  service:
    targetPort: 8000

portal:
  enabled: true
  service:
    targetPort: 80
  image:
      repository: quay.io/cdis/data-portal-prebuilt
      tag: dev

requestor:
  enabled: false
  service:
    targetPort: 8000

revproxy:
  enabled: true
  nginx:
    resolver: "dns-default.openshift-dns.svc.cluster.local"
  # -- (map) Configuration for OpenShift Route.
  openshiftRoute:
    # -- (bool) Whether to create an OpenShift Route
    enabled: true
    # -- (map) Annotations to add to the Route.
    annotations: {}
    # -- (string) Hostname for the Route. Leave empty to let OpenShift auto-generate
    host: "gen3.apps-crc.testing"
    # -- (string) Path for the Route.
    path: "/"
    # -- (string) Target port for the Route.
    targetPort: "http"
    # -- (map) TLS configuration for the Route.
    tls:
      # -- (string) Termination type for the Route. Valid options are "edge", "passthrough", and "reencrypt".
      termination: "edge"
      # -- (string) Insecure edge termination policy. Valid options are "None", "Allow", and "Redirect".
      insecureEdgeTerminationPolicy: "Redirect"
    # -- (string) Wildcard policy for the Route. Valid options are "None" and "Subdomain".
    wildcardPolicy: "None"


sheepdog:
  # -- (bool) Whether to deploy the sheepdog subchart.
  enabled: true
  service:
    targetPort: 8000

ssjdispatcher:
  # -- (bool) Whether to deploy the ssjdispatcher subchart.
  enabled: false
  service:
    targetPort: 8080

wts:
  # -- (bool) Whether to deploy the wts subchart.
  enabled: true
  oidc_job_openshift: true
  service:
    targetPort: 8000

sower:
  enabled: false
  service:
    targetPort: 8000

ohif-viewer:
  enabled: false
  service:
    targetPort: 8080

dicom-server:
  enabled: false
  service:
    targetPort: 8042

access-backend:
  enabled: false
  service:
    targetPort: 8001

postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: 16.6.0-debian-12-r2
  primary:
    persistence:
      # -- (bool) Option to persist the dbs data.
      enabled: false
    podSecurityContext:
      enabled: false
      fsGroup: 1000660001
    containerSecurityContext:
      enabled: false
      runAsUser: 1000660001
      allowPrivilegeEscalation: false
      seccompProfile:
        type: "RuntimeDefault"

elasticsearch:
  image: "quay.io/cdis/elasticsearch"
  imageTag: "7.10.2"
  clusterName: gen3-elasticsearch
  maxUnavailable: 0
  singleNode: true
  replicas: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  esConfig:
    elasticsearch.yml: |
      # Here we can add elasticsearch config
  podSecurityContext:
    enabled: false
    fsGroup: 1000
    runAsUser: 1000

  securityContext:
    enabled: false
    capabilities:
      drop:
      - ALL
    # readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

