apiVersion: v1
kind: Service
metadata:
  name: fence-service
  labels:
    {{- include "fence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (eq (include "common.nginxSidecar.servicePortName" .) "https") }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "fence.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: presigned-url-fence-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (eq (include "common.nginxSidecar.servicePortName" .) "https") }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: http
  selector:
    app: presigned-url-fence

