{{- if .Values.migrations.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vectis-db-migration-creds
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Release.Namespace }}
    kind: ClusterSecretStore
  target:
    name: vectis-db-migration-creds
    creationPolicy: Owner
    template:
      data:
        host: "{{ .Values.rds.endpoint }}"
        username: "{{ `{{.username}}` }}"
        password: "{{ `{{.password}}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.rds.secretName }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.rds.secretName }}
        property: password
{{- end }}
