{{- if .Values.s3Monitor.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.s3Monitor.db.secretTargetName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    {{- if ne .Values.global.externalSecrets.clusterSecretStoreRef  "" }}
      name: {{ .Values.global.externalSecrets.clusterSecretStoreRef }}
      kind: ClusterSecretStore
    {{- else }}
      name: {{include "common.SecretStore" .}}
      kind: SecretStore
    {{- end }}
  target:
    name: {{ .Values.s3Monitor.db.secretTargetName }}
    creationPolicy: Owner
    template:
      data:
        PGHOST: {{ .Values.s3Monitor.db.host | quote }}
        PGPORT: {{ .Values.s3Monitor.db.port | quote }}
        PGDATABASE: {{ .Values.s3Monitor.db.database | quote }}
        PGUSER: "{{ `{{.username}}` }}"
        PGPASSWORD: "{{ `{{.password}}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.s3Monitor.db.secretName }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.s3Monitor.db.secretName }}
        property: password
{{- end }}
