{{- if .Values.searchAuthProxy.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vectis-search-auth-proxy
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    # name: {{ .Release.Namespace }}
    # kind: ClusterSecretStore
    {{- if ne .Values.global.externalSecrets.clusterSecretStoreRef  "" }}
      name: {{ .Values.global.externalSecrets.clusterSecretStoreRef }}
      kind: ClusterSecretStore
    {{- else }}
      name: {{include "common.SecretStore" .}}
      kind: SecretStore
    {{- end  }}
  target:
    name: vectis-search-auth-proxy
    creationPolicy: Owner
    template:
      data:
        postgres_dsn: "postgresql://{{ `{{.username}}` }}:{{ `{{.password}}` }}@{{ .Values.rds.endpoint }}:{{ .Values.rds.port }}/{{ .Values.rds.database }}"
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.rds.secretName }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.rds.secretName }}
        property: password
{{- end }}
