{{- $global := .Values.global | default dict }}
{{- $crossplane := get $global "crossplane" | default dict }}
{{- $crossplaneEnabled := get $crossplane "enabled" | default false }}
{{- if and .Values.guppyCompat.enabled .Values.guppyCompat.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.guppyCompat.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.guppyCompat.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.siemService.enabled .Values.siemService.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.siemService.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.siemService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if and .Values.searchAuthProxy.enabled .Values.searchAuthProxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.searchAuthProxy.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- if $crossplaneEnabled }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ get $crossplane "accountId" }}:role/{{ get $global "environment" }}-{{ .Release.Namespace }}-{{ .Values.searchAuthProxy.serviceAccount.name }}
  {{- else }}
  {{- with .Values.searchAuthProxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
