location /fhir/ {
    # This is for revproxy logging/metrics
    set $proxy_service "fhir-proxy";
    
    # Add header to indicate that the request was routed through fhir-proxy (useful for logging/metrics)
    add_header X-FHIR-PROXY-ROUTE hit always;

    # The following was commented out, because it seemed not needed
    # rewrite ^/fhir/(.*)$ /$1 break;

    # #======================================================
    # # When locally running fhir-proxy OUTSIDE the gen3 helm chart:
    # set $upstream http://host.docker.internal:8007;
    # proxy_pass $upstream;
    # # Note that in this setup test endpoints are reached via
    # # curl http://localhost:8007/test
    # # curl http://localhost:8007/_version
    # # while curl http://localhost:8081/fhir/Patient is the route for actual fhir requests 


    # When locally running fhir-proxy INSIDE the gen3 helm chart:
    proxy_pass http://fhir-proxy.gen3-ns.svc.cluster.local:8007/;
    
    # Optional: adjust if your proxy needs large uploads or long-running requests
    # client_max_body_size 0;
    # proxy_read_timeout 300;
    proxy_set_header Authorization "$access_token";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For "$realip";
    proxy_set_header X-UserId "$userid";
    proxy_set_header X-ReqId "$request_id";
    proxy_set_header X-SessionId "$session_id";
    proxy_set_header X-VisitorId "$visitor_id";
}