location /fhir/ {
    # #======================================================
    # # When running fhir-proxy OUTSIDE the gen3 helm chart:
    # # This is for revproxy logging/metrics
    # set $proxy_service "fhir-proxy";
    # # Upstream: external endpoint (e.g., local Docker, another host)
    # set $upstream http://host.docker.internal:8007;

    # # The following was commented out, because when running fhir-proxy
    # # outside the gen3 helm chart it seemed not needed
    # # # Strip the prefix before sending to upstream
    # # # Meaning /fhir/Patient/123 will be sent to the 
    # # # upstream as /Patient/123
    # # rewrite ^/fhir/(.*)$ /$1 break;
    # proxy_pass $upstream;

    # #======================================================
    # When running fhir-proxy INSIDE the gen3 helm chart:
    # This is for revproxy logging/metrics
    set $proxy_service "fhir-proxy";
    # Upstream: external endpoint (e.g., local Docker, another host)
    set $upstream http://fhir-proxy.$namespace.svc.cluster.local:8007;

    # The following was commented out, because when running fhir-proxy
    # outside the gen3 helm chart it seemed not needed
    # # Strip the prefix before sending to upstream
    # # Meaning /fhir/Patient/123 will be sent to the 
    # # upstream as /Patient/123
    rewrite ^/fhir/(.*)$ /$1 break;
    proxy_pass $upstream;

    # Optional: adjust if your proxy needs large uploads or long-running requests
    # client_max_body_size 0;
    # proxy_read_timeout 300;
}