location /fhir/ {
    # #======================================================
    # # When running fhir-proxy OUTSIDE the gen3 helm chart:
    # # This is for revproxy logging/metrics
    # set $proxy_service "fhir-proxy";
    # # Upstream: external endpoint (e.g., local Docker, another host)
    # set $upstream http://host.docker.internal:8007;

    # # The following was commented out, because when running fhir-proxy
    # # outside the gen3 helm chart it seemed not needed
    # # # Strip the prefix before sending to upstream
    # # # Meaning /fhir/Patient/123 will be sent to the 
    # # # upstream as /Patient/123
    # # rewrite ^/fhir/(.*)$ /$1 break;
    # proxy_pass $upstream;

    # #======================================================
    # When running fhir-proxy INSIDE the gen3 helm chart:
    # This is for revproxy logging/metrics
    set $proxy_service "fhir-proxy";
    # Upstream: external endpoint (e.g., local Docker, another host)
    # set $upstream http://fhir-proxy.$namespace.svc.cluster.local:8007/;
    
    # Add header to indicate that the request was routed through fhir-proxy (useful for logging/metrics)
    # add_header X-FHIR-PROXY-ROUTE hit always;

    # The following was commented out, because when running fhir-proxy
    # inside the gen3 helm chart it seemed not needed
    # nginx already does this automatically
    # # Strip the prefix before sending to upstream
    # # Meaning /fhir/Patient/123 will be sent to the 
    # # upstream as /Patient/123
    
    # # rewrite ^/fhir/(.*)$ /$1 break; 
        
    # avoid using variables like upstream and namespace, because 
    # it is not needed and it makes the nginx config more complex than necessary
    # at least for local testing
    proxy_pass http://fhir-proxy.gen3-ns.svc.cluster.local:8007/;
    
    # Optional: adjust if your proxy needs large uploads or long-running requests
    # client_max_body_size 0;
    # proxy_read_timeout 300;
    proxy_set_header Authorization "$access_token";
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For "$realip";
    proxy_set_header X-UserId "$userid";
    proxy_set_header X-ReqId "$request_id";
    proxy_set_header X-SessionId "$session_id";
    proxy_set_header X-VisitorId "$visitor_id";
}