location /fhir/ {
    # This is for revproxy logging/metrics
    set $proxy_service "gen3-fhir-proxy";
    # Upstream: external endpoint (e.g., local Docker, another host)
    set $upstream http://host.docker.internal:8007;

    # # Strip the prefix before sending to upstream
    # # Meaning /fhir/Patient/123 will be sent to the 
    # # upstream as /Patient/123
    # rewrite ^/fhir/(.*)$ /$1 break;

    proxy_pass $upstream;

    # # Standard headers
    # proxy_set_header Host              $host;
    # proxy_set_header X-Real-IP         $remote_addr;
    # proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    # proxy_set_header X-Forwarded-Proto $scheme;

    # Optional: adjust if your proxy needs large uploads or long-running requests
    # client_max_body_size 0;
    # proxy_read_timeout 300;
}