# Model repository API is exposed through the Gen3 AI namespace.
location /ai/models {
    if ($csrf_check !~ ^ok-\S.+$) {
        return 403 "failed csrf check";
    }

    set $proxy_service "gen3-ai-model-repo-service";
    set $upstream http://gen3-ai-model-repo-service$des_domain;
    rewrite ^/ai/models/(.*) /api/models/$1 break;
    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/ai/models/;
    client_max_body_size 0;
}