# The Gen3 Embeddings service is deployed as part of the overall Gen3 AI
# support. Everything in Gen3 AI is available at the `/ai` route.
# This file defines routing from there to the Gen3 Embeddings service 
# for functionality it handles.

location /ai/vectorstore {
    if ($csrf_check !~ ^ok-\S.+$) {
        return 403 "failed csrf check";
    }

    set $proxy_service  "gen3-embeddings-service";
    set $upstream http://gen3-embeddings-service$des_domain;
    rewrite ^/ai/vectorstore/(.*) /vectorstore/$1 break;
    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/ai/vectorstore/;
    client_max_body_size 0;
}

location /ai/embeddings {
    if ($csrf_check !~ ^ok-\S.+$) {
        return 403 "failed csrf check";
    }

    set $proxy_service  "gen3-embeddings-service";
    set $upstream http://gen3-embeddings-service$des_domain;
    rewrite ^/ai/embeddings/(.*) /embeddings/$1 break;
    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/ai/embeddings/;
    client_max_body_size 0;
}

location /ai/embeddings/_version {
    if ($csrf_check !~ ^ok-\S.+$) {
        return 403 "failed csrf check";
    }

    set $proxy_service  "gen3-embeddings-service";
    set $upstream http://gen3-embeddings-service$des_domain;
    rewrite ^/ai/embeddings/_version /_version break;
    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/ai/embeddings/_version;
    client_max_body_size 0;
}

location /ai/embeddings/_status {
    if ($csrf_check !~ ^ok-\S.+$) {
        return 403 "failed csrf check";
    }

    set $proxy_service  "gen3-embeddings-service";
    set $upstream http://gen3-embeddings-service$des_domain;
    rewrite ^/ai/embeddings/_status /_status break;
    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/ai/embeddings/_status;
    client_max_body_size 0;
}
