location /embeddings {
    if ($csrf_check !~ ^ok-\S.+$) {
    return 403 "failed csrf check";
    }

    set $proxy_service  "gen3-embeddings-service";
    set $upstream http://gen3-embeddings-service$des_domain;
    rewrite ^/embeddings/(.*) /$1 break;
    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/embeddings/;
    client_max_body_size 0;
}
