apiVersion: v1
kind: Service
metadata:
  name: "metadata-service"
  {{- with .Values.serviceAnnotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "metadata.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ ternary 443 .Values.service.port (eq (include "common.nginxSidecar.servicePortName" .) "https") }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}