apiVersion: v2
name: vectis-overlays
description: Vectis overlay API services (guppy-compat, siem, search-auth-proxy)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: common
    version: 0.1.34
    repository: file://../common
