apiVersion: v1
entries:
  mongodb:
  - annotations:
      category: Database
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 6.0.5
    created: "2026-01-28T19:22:15.476017-08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 2.x.x
    description: MongoDB(R) is a relational open source NoSQL database. Easy to use,
      it stores data in JSON-like documents. Automated scalability and high-performance.
      Ideal for developing cloud native applications.
    digest: 72cad96eeef97b7ae63feaa5ee57244f793cacb5dc867af4fdcbcf65bb67501c
    home: https://github.com/bitnami/charts/tree/main/bitnami/mongodb
    icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
    keywords:
    - mongodb
    - database
    - nosql
    - cluster
    - replicaset
    - replication
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: mongodb
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/mongodb
    - https://mongodb.org
    urls:
    - charts/mongodb-13.9.4.tgz
    version: 13.9.4
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 14.5.0
    created: "2026-01-28T19:22:15.479517-08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: fd7937464e52c1e643c45cbbf3758bcedfab41753d6cb34c6b4969ec1d77d0e8
    home: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Bitnami
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/containers/tree/main/bitnami/postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-11.9.13.tgz
    version: 11.9.13
generated: "2026-01-28T19:22:15.472097-08:00"
