apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mock-jwt-issuer.fullname" . }}-server
  labels:
    {{- include "mock-jwt-issuer.labels" . | nindent 4 }}
data:
  server.py: |
{{ .Files.Get "files/server.py" | indent 4 }}
