{{- if .Values.jwtKeys.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mock-jwt-issuer.fullname" . }}-jwt-keys
  labels:
    {{- include "mock-jwt-issuer.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_private_key.pem: |
{{ .Values.jwtKeys.privateKey | indent 4 }}
{{- end }}
