apiVersion: v2
name: gen3-workflow
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
version: 0.1.18
=======
version: 0.1.11
>>>>>>> 10573193 (Update funnel to 0.1.53 and update netpols accordingly)
=======
version: 0.1.1
>>>>>>> d0be3cc5 (Update versions to meet with Lint changes)
=======
version: 0.1.2
>>>>>>> 9cc23438 (Update PV Template in funnel to add flags to csi driver config)
=======
version: 0.1.3
>>>>>>> d89729c9 (Update Gen3Workflow secrets to include EKS cluster variables)
=======
version: 0.1.4
>>>>>>> fd4a8a32 (Fix YAML indentation in Gen3-workflow config)
=======
version: 0.1.5
>>>>>>> ab9a5ede (Update gen3-workflow version)
=======
version: 0.1.6
>>>>>>> 54d92d69 (Karpenter Tology Spread  (#460))
=======
version: 0.1.7
>>>>>>> a21aca21 (Update IAM role in gen3-workflow crossplane.yaml (#468))
=======
version: 0.1.8
>>>>>>> d7adb420 (Improve gen3-workflow to run out of the box)
=======
version: 0.1.9
>>>>>>> 94864c64 (Bump gen3-workflow chart)
=======
version: 0.1.10
>>>>>>> 9e2b9ff6 (Update funnel to 0.1.80)
=======
version: 0.1.11
>>>>>>> df289989 (MIDRC-1193 Postgres DB for Funnel (#503))
=======
version: 0.1.12
>>>>>>> 60329e41 (Allow overriding bucket name for manifestservice (#522))
=======
version: 0.1.13
>>>>>>> b2d6fd08 (MIDRC-1193 Remove Funnel mongodb netpolicies (#512))
=======
version: 0.1.14
>>>>>>> f9570c4e (MIDRC-1228 gen3-workflow AbortMultipartUpload access (#533))

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "master"

dependencies:
  - name: common
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    version: 0.1.34
=======
    version: 0.1.24
>>>>>>> f57d39fd (Update common chart version across the board)
=======
    version: 0.1.25
>>>>>>> 950b51ce (Update version of common and gen3 charts)
=======
    version: 0.1.24
>>>>>>> dabe938c (Revert "Update version of common and gen3 charts")
=======
    version: 0.1.25
>>>>>>> d0be3cc5 (Update versions to meet with Lint changes)
=======
    version: 0.1.26
>>>>>>> 14bf12cf ( Setup PushSecret for DB init (#433))
=======
    version: 0.1.28
>>>>>>> 54d92d69 (Karpenter Tology Spread  (#460))
=======
    version: 0.1.33
>>>>>>> b2d6fd08 (MIDRC-1193 Remove Funnel mongodb netpolicies (#512))
    repository: file://../common
<<<<<<< HEAD
=======
  - name: funnel
<<<<<<< HEAD
<<<<<<< HEAD
    version: 0.1.50
    repository: "file://../funnel"
>>>>>>> ac9ee302 (Add useryaml, update funnel secrets, add funnel local chart reference)
=======
    version: 0.1.53
=======
    # NOTE:
    # When updating this version:
    # 1) Run `helm dependency update` to generate a new .tgz file
    # 2) Commit the updated .tgz file into gen3-helm in the same PR
    #
    # ArgoCD relies on this checked-in .tgz reference — if it's missing,
    # Funnel will not be deployed as a dependency.
    version: 0.1.80
>>>>>>> 9e2b9ff6 (Update funnel to 0.1.80)
    repository: "https://ohsu-comp-bio.github.io/helm-charts"
>>>>>>> 10573193 (Update funnel to 0.1.53 and update netpols accordingly)
=======
    version: 0.1.30
=======
    version: 0.1.31
>>>>>>> 60329e41 (Allow overriding bucket name for manifestservice (#522))
    repository: file://../common
>>>>>>> df289989 (MIDRC-1193 Postgres DB for Funnel (#503))
