{{- if and .Values.global.externalSecrets.deploy (not .Values.global.externalSecrets.createLocalK8sSecret) }}
{{ include "common.externalSecret.db" . }}
{{- end }}

{{- if and .Values.global.externalSecrets.deploy (not .Values.externalSecrets.createK8sRequestorSecret) }}
---
apiVersion: {{ include "common.externalSecrets.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: requestor-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ include "common.SecretStore" . }}
    kind: SecretStore
  target:
    name: requestor-g3auto
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        key: {{ include "requestor-g3auto" . }}
        property: config.yaml
{{- end }}