{{- if or (not .Values.global.externalSecrets.deploy) .Values.externalSecrets.createK8sRequestorSecret }}
{{- if .Values.requestorConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: requestor-g3auto
type: Opaque
stringData:
  config.yaml: |
{{ .Values.requestorConfig.configYaml | indent 4 }}
{{- end }}
{{- end }}