apiVersion: v1
kind: Service
metadata:
  name: revproxy-service
  labels:
    {{- include "revproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ ternary 443 .Values.service.port (and $nginx.enabled $nginx.tls.enabled) }}
      targetPort: {{ ternary "https" "http" (and $nginx.enabled $nginx.tls.enabled) }}
      protocol: TCP
      name: {{ ternary "https" "http" (and $nginx.enabled $nginx.tls.enabled) }}
  selector:
    {{- include "revproxy.selectorLabels" . | nindent 4 }}