# Default values for terraform-runner-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: "master"

credentials:
  aws:
    key: ""
    secret: ""
    session_token: ""
    # -- (string) AWS region for this deployment
    region: "us-east-1"

terraform:
  resource_name: ""
  workspace_name: ""
  destroy: false
