apiVersion: apps/v1
kind: Deployment
metadata:
  name: zendesk-wrapper-deployment
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "zendesk-wrapper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zendesk-wrapper.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "zendesk-wrapper.selectorLabels" . | nindent 8 }}
        {{- include "common.extraLabels" . | nindent 8 }}
        netnolimit: 'yes'
        public: 'yes'
    spec:
      {{- if .Values.global.topologySpread.enabled }}
      {{- include "common.TopologySpread" . | nindent 6 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          readinessProbe:
            httpGet:
              path: /_status/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /_status/
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 6
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - /src/start.sh
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            - name: ZENDESK_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: zendesk-wrapper-secret
                  key: clientSecret
            - name: ZENDESK_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: zendesk-wrapper-secret
                  key: clientID
