---
{{- if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zendesk-wrapper-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: zendesk-wrapper-secret
    creationPolicy: Owner
  data:
  - secretKey: tokenKey
    remoteRef:
      key: zendesk-wrapper-secret
      property: tokenKey
  - secretKey: apiEmail
    remoteRef:
      key: zendesk-wrapper-secret
      property: apiEmail
{{- end }}
