apiVersion: v1
kind: Service
metadata:
  name: "frontend-framework-service"
  labels:
    {{- include "frontend-framework.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ ternary 443 .Values.service.port (and $nginx.enabled $nginx.tls.enabled) }}
      targetPort: {{ include "common.nginxSidecar.targetPortName" . }}
      protocol: TCP
      name: {{ include "common.nginxSidecar.servicePortName" . }}  
    - protocol: TCP
      port: 443
      targetPort: {{ .Values.port }}
      name: https
  type: ClusterIP
  selector:
    {{- include "frontend-framework.selectorLabels" . | nindent 4 }}
