{{- if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gen3aimodelrepo-g3auto
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ include "common.SecretStore" . }}
    kind: SecretStore
  target:
    name: gen3aimodelrepo-g3auto
    creationPolicy: Owner
  data:
    - secretKey: gen3-ai-model-repo.env
      remoteRef:
        key: {{ include "gen3aimodelrepo-g3auto" . }}
        property: gen3-ai-model-repo.env
{{- end }}
---
{{- if and .Values.global.externalSecrets.deploy (not .Values.global.externalSecrets.createLocalK8sSecret) }}
{{ include "common.externalSecret.db" . }}
{{- end }}