{{- if or (not .Values.global.externalSecrets.deploy) (and .Values.global.externalSecrets.deploy .Values.externalSecrets.createK8sGen3AiModelRepoSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: gen3aimodelrepo-g3auto
stringData:
  gen3-ai-model-repo.env: |
    DEBUG={{ .Values.debug }}
    DB_HOST={{ .Values.postgres.host }}
    DB_PORT={{ .Values.postgres.port }}
    DB_USER={{ .Values.postgres.username }}
    DB_PASSWORD={{ include "gen3-ai-model-repo.postgres.password" . }}
    DB_DATABASE={{ .Values.postgres.database }}
    GUNICORN_WORKERS={{ .Values.gunicornWorkers }}
    STORAGE_PROVIDER={{ .Values.storage.provider }}
    LOCAL_STORAGE_PATH={{ .Values.storage.localPath }}
{{- end }}