{{- if and .Values.global.externalSecrets.deploy .Values.global.externalSecrets.separateSecretStore (not (default false .Values.global.aws.useLocalSecret.enabled)) }}
{{ include "common.secretstore" . }}
{{- end }}